### ISSUE TITLE
SyntaxWarning: FilerFileField can only be a ForeignKey to File; filer.File passed

### ISSUE THREAD

**Issue by hebijiandai** [stefanfoulis/django-filer#466]
Hello sir,thanks for design this app,I try to lay out in my computer,but it cause the errors,how can I fix it?
Thanks!

```
/Library/Python/2.7/site-packages/filer/fields/file.py:118: SyntaxWarning: FilerFileField can only be a ForeignKey to File; filer.File passed
  warnings.warn(msg, SyntaxWarning)

Operations to perform:
  Synchronize unmigrated apps: filer, suit_ckeditor, staticfiles, suit, messages, django_select2, django_extensions, suit_redactor, import_export
  Apply all migrations: sessions, admin, auth, reversion, contenttypes, main, easy_thumbnails
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  No migrations to apply.
/Library/Python/2.7/site-packages/filer/fields/multistorage_file.py:106: SyntaxWarning: MultiStorageFileField can handle only File objects;<function generate_filename_multistorage at 0x1038df9b0> passed
  "%s passed" % upload_to, SyntaxWarning)


```

**Comment by yakky** [comment]
Have you setup ``MIGRATION_MODULES`` like documented in https://github.com/stefanfoulis/django-filer#django-17

**Comment by radlws** [comment]
I'm migrating from django 1.6, I tried by deleting the db and starting over, got this on migrate

```
Operations to perform:
  Synchronize unmigrated apps: solo, mptt, menu, trapeze, tinymce, locking, theming, debug_toolbar, dashboard, rest_framework, longerusername, admin_tools, raven_compat, requests, localflavor
  Apply all migrations: filer, sessions, admin, sites, auth, contenttypes, worksheets, easy_thumbnails, projects, user_profiles
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying auth.0002_auto_20150105_0024... OK
  Applying filer.0001_initial... FAKED
  Applying filer.0002_image...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/pilsner/projects/baker/site/lib/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/pilsner/projects/baker/site/lib/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/pilsner/projects/baker/site/lib/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/pilsner/projects/baker/site/lib/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/pilsner/projects/baker/site/lib/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/pilsner/projects/baker/site/lib/django/db/migrations/operations/models.py", line 36, in database_forwards
    schema_editor.create_model(model)
  File "/home/pilsner/projects/baker/site/lib/django/db/backends/schema.py", line 262, in create_model
    self.execute(sql, params)
  File "/home/pilsner/projects/baker/site/lib/django/db/backends/schema.py", line 103, in execute
    cursor.execute(sql, params)
  File "/home/pilsner/projects/baker/site/lib/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/pilsner/projects/baker/site/lib/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/pilsner/projects/baker/site/lib/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/pilsner/projects/baker/site/lib/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "filer_image" already exists
```

**Comment by yakky** [comment]
A fix for this has just been merged, it will be released in 0.9.9 soon

**Comment by radlws** [comment]
Cool thanks for the update

**Comment by radlws** [comment]
Also seeing this now, it may be a different issue all together:

filer/fields/multistorage_file.py:106: SyntaxWarning: MultiStorageFileField can handle only File objects;<function generate_filename_multistorage at 0x10288fde8> passed
  "%s passed" % upload_to, SyntaxWarning)

**Comment by Bartvds** [comment]
+1 for a release containing this fix

**Comment by yakky** [comment]
@Bartvds @radlws @hebijiandai please check #496 which should solve this issue

**Comment by hebijiandai** [comment]
Thanks for your help!I wish you too continue concern this wonderful project!
