### ISSUE TITLE
Django 1.8 breaks filer

### ISSUE THREAD

**Issue by radlws** [stefanfoulis/django-filer#513]
Here is the traceback, 

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/projects/baker/site/lib/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/projects/baker/site/lib/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/vagrant/projects/baker/site/lib/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/projects/baker/site/lib/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/vagrant/projects/baker/site/lib/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/projects/baker/site/lib/filer/models/__init__.py", line 2, in <module>
    from filer.models.clipboardmodels import *
  File "/home/vagrant/projects/baker/site/lib/filer/models/clipboardmodels.py", line 7, in <module>
    from filer.models import filemodels
  File "/home/vagrant/projects/baker/site/lib/filer/models/filemodels.py", line 12, in <module>
    from filer.models.foldermodels import Folder
  File "/home/vagrant/projects/baker/site/lib/filer/models/foldermodels.py", line 228, in <module>
    mptt.register(Folder)
  File "/home/vagrant/projects/baker/site/lib/mptt/__init__.py", line 14, in register
    return MPTTModelBase.register(*args, **kwargs)
  File "/home/vagrant/projects/baker/site/lib/mptt/models.py", line 338, in register
    tree_manager.init_from_model(cls)
  File "/home/vagrant/projects/baker/site/lib/mptt/managers.py", line 52, in init_from_model
    [tree_field] = [fld for fld in model._meta.get_fields_with_model() if fld[0].name == self.tree_id_attr]
  File "/home/vagrant/projects/baker/site/lib/django/db/models/options.py", line 56, in wrapper
    return fn(*args, **kwargs)
  File "/home/vagrant/projects/baker/site/lib/django/db/models/options.py", line 432, in get_fields_with_model
    return [self._map_model(f) for f in self.get_fields()]
  File "/home/vagrant/projects/baker/site/lib/django/db/models/options.py", line 740, in get_fields
    return self._get_fields(include_parents=include_parents, include_hidden=include_hidden)
  File "/home/vagrant/projects/baker/site/lib/django/db/models/options.py", line 802, in _get_fields
    all_fields = self._relation_tree
  File "/home/vagrant/projects/baker/site/lib/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vagrant/projects/baker/site/lib/django/db/models/options.py", line 709, in _relation_tree
    return self._populate_directed_relation_graph()
  File "/home/vagrant/projects/baker/site/lib/django/db/models/options.py", line 681, in _populate_directed_relation_graph
    all_models = self.apps.get_models(include_auto_created=True)
  File "/home/vagrant/projects/baker/site/lib/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/vagrant/projects/baker/site/lib/django/apps/registry.py", line 168, in get_models
    self.check_models_ready()
  File "/home/vagrant/projects/baker/site/lib/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by xrmx** [comment]
That's an old mptt breaking django 1.8, upgrade to 0.7.1 and it would work. 
django-filer is broken by polymorphic though:
```
  File "/home/rm/src/django-admin-bootstrapped/testenv/local/lib/python2.7/site-packages/polymorphic/query.py", line 13, in <module>
    from .query_translate import translate_polymorphic_filter_definitions_in_kwargs, translate_polymorphic_filter_definitions_in_args
  File "/home/rm/src/django-admin-bootstrapped/testenv/local/lib/python2.7/site-packages/polymorphic/query_translate.py", line 10, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related
```
See polymorphic bug here:
https://github.com/chrisglass/django_polymorphic/issues/116

**Comment by radlws** [comment]
Thanks, I'll wait for an update to polymorphic.

**Comment by radlws** [comment]
All fixed now. Thanks.
