### ISSUE TITLE
[django 1.8] AttributeError: 'FileAdmin' object has no attribute 'queryset'

### ISSUE THREAD

**Issue by bashu** [stefanfoulis/django-filer#528]
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/src/django-filer/filer/admin/fileadmin.py", line 100, in delete_view
    obj = self.queryset(request).get(pk=unquote(object_id))
AttributeError: 'FileAdmin' object has no attribute 'queryset'
```

**Comment by radlws** [comment]
I'm still getting the error when deleting. Is this supposed to be fixed?

**Comment by radlws** [comment]
Here is the traceback, version I'm using is 0.9.10a1.dev1 . Looks like the version hasn't changed since the beginning of May.

```
Internal Server Error: /cmsadmin/filer/file/759/delete/ 
Traceback (most recent call last): 
  File "/home/bakerteam/live/deploys/20150519-154152/site/lib/django/core/handlers/base.py", line 132, in get_response 
    response = wrapped_callback(request, *callback_args, **callback_kwargs) 
  File "/home/bakerteam/live/deploys/20150519-154152/site/lib/django/contrib/admin/options.py", line 616, in wrapper 
    return self.admin_site.admin_view(view)(*args, **kwargs) 
  File "/home/bakerteam/live/deploys/20150519-154152/site/lib/django/utils/decorators.py", line 110, in _wrapped_view 
    response = view_func(request, *args, **kwargs) 
  File "/home/bakerteam/live/deploys/20150519-154152/site/lib/django/views/decorators/cache.py", line 57, in _wrapped_view_func 
    response = view_func(request, *args, **kwargs) 
  File "/home/bakerteam/live/deploys/20150519-154152/site/lib/django/contrib/admin/sites.py", line 233, in inner 
    return view(request, *args, **kwargs) 
  File "/home/bakerteam/live/deploys/20150519-154152/site/lib/filer/admin/fileadmin.py", line 100, in delete_view 
    obj = self.queryset(request).get(pk=unquote(object_id)) 
AttributeError: 'FileAdmin' object has no attribute 'queryset' 

Request repr(): 
<WSGIRequest 
path:/cmsadmin/filer/file/759/delete/, 
GET:<QueryDict: {u'_popup': [u'1']}>, 
POST:<QueryDict: {}>, 
COOKIES:{'__utma': '237384732.437251584.1403119442.1431718883.1432071849.165', 
 '__utmb': '237384732.5.10.1432071849', 
 '__utmc': '237384732', 
 '__utmt': '1', 
 '__utmz': '237384732.1431091434.160.6.utmcsr=eb02.executivemailingservices.com|utmccn=(referral)|utmcmd=referral|utmcct=/Site/s/c.aspx', 
 '_ga': 'GA1.2.437251584.1403119442', 
 'csrftoken': 'VEeXutdTIyLV0nmxPABmggQffDd8y7je', 
 'sessionid': 'v5nb18oi6g2l8bpr65qbuxkugcopzrbr'}, 
META:{u'CSRF_COOKIE': u'VEeXutdTIyLV0nmxPABmggQffDd8y7je', 
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch', 
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8', 
 'HTTP_CONNECTION': 'close', 
 'HTTP_COOKIE': '_ga=GA1.2.437251584.1403119442; __utmt=1; __utma=237384732.437251584.1403119442.1431718883.1432071849.165; __utmb=237384732.5.10.1432071849; __utmc=237384732; __utmz=237384732.1431091434.160.6.utmcsr=eb02.executivemailingservices.com|utmccn=(referral)|utmcmd=referral|utmcct=/Site/s/c.aspx; csrftoken=VEeXutdTIyLV0nmxPABmggQffDd8y7je; sessionid=v5nb18oi6g2l8bpr65qbuxkugcopzrbr', 
 'HTTP_HOST': 'mydomain.com', 
 'HTTP_REFERER': 'http://mybaker.bakerrealtypartners.com/cmsadmin/filer/folder/54/list/?_to_field=id&_popup=1', 
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36', 
 'HTTP_X_FORWARDED_FOR': '38.112.92.34', 
 'HTTP_X_FORWARDED_PROTOCOL': 'http', 
 'HTTP_X_REAL_IP': '38.112.92.34', 
 'PATH_INFO': u'/cmsadmin/filer/file/759/delete/', 
 'QUERY_STRING': '_popup=1', 
 'RAW_URI': '/cmsadmin/filer/file/759/delete/?_popup=1', 
 'REMOTE_ADDR': '', 
 'REQUEST_METHOD': 'GET', 
 'SCRIPT_NAME': u'', 
 'SERVER_NAME': 'mydomain.com', 
 'SERVER_PORT': '80', 
 'SERVER_PROTOCOL': 'HTTP/1.0', 
 'SERVER_SOFTWARE': 'gunicorn/19.1.1', 
 'gunicorn.socket': <socket._socketobject object at 0x56bebb0>, 
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWraper object at 0x591bd10>, 
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>, 
 'wsgi.input': <gunicorn.http.body.Body object at 0x581bf90>, 
 'wsgi.multiprocess': True, 
 'wsgi.multithread': False, 
 'wsgi.run_once': False, 
 'wsgi.url_scheme': 'http', 
 'wsgi.version': (1, 0)}> 
```

**Comment by bashu** [comment]
here is a fix https://github.com/stefanfoulis/django-filer/pull/535

**Comment by bashu** [comment]
already fixed in 'develop' branch
